Fixed bug when specifying a delay
The division in the 'loop' calculation in perform() was returning floating point values
after the migration to Python 3, rather than rounding down. Changed to floor division.

I think the floating point values kept 'loop == 0' from ever being
true and the variables inside that conditional were never initialized,
causing the following error when a delay other than 1 was specified:

You did not select any stats, using -cdngy by default.
Traceback (most recent call last):
  File "/home/falko/repos/dstat/dstat", line 2825, in <module>
    main()
  File "/home/falko/repos/dstat/dstat", line 2684, in main
    scheduler.run()
  File "/home/falko/.conda/envs/python3/lib/python3.7/sched.py", line 151, in run
    action(*argument, **kwargs)
  File "/home/falko/repos/dstat/dstat", line 2729, in perform
    oldcols = cols
NameError: name 'cols' is not defined